export enum ErrorCode {
  NAVIGATING = "NAVIGATING",
  AUTH_REQUIRED = "AUTH_REQUIRED",
  SIDEBAR_NOT_FOUND = "SIDEBAR_NOT_FOUND",
  COLLECTION_NOT_FOUND = "COLLECTION_NOT_FOUND",
  PARSE_ERROR = "PARSE_ERROR",
  MISSING_ID = "MISSING_ID",
  STATUS_MISSING = "STATUS_MISSING",
  CATEGORY_MISSING = "CATEGORY_MISSING",
  DATA_INCONSISTENCY = "DATA_INCONSISTENCY",
}
